### PR TITLE
Voice command

### PR DESCRIPTION
**Pull request by flooie**
Added installation of Snowboy for voice recognition

### CODE REVIEW

**Comment by flooie** [comment]
its a little slow - but it works

**Comment by chenguoguo** [comment]
Great work @flooie !

One small comment, the pmdl models are called personal models, and are only supposed to work well for the person who record them. We also provide universal models that works for everyone, but we only train such models when we collect enough data. So at this point, other uses will have to go to our website (snowboy.kitt.ai), create their own personal models, and replace your Alexa.pmdl, Charlie.pmdl with their own.

Also, we just added VAD (see here [Kitt-AI/snowboy#3](https://github.com/Kitt-AI/snowboy/issues/3)) and hopefully that will improve the user experience.

**Comment by sammachin** [comment]
I'm just waiting on an answer from the AVS team about adding wake word detection, my understanding of  AVS Requirements Agreement Clause 2m: 
"you will not implement far-field voice recognition or use of a spoken word to trigger the activation of the Alexa Service in Your Products without Amazon's prior written approval and any such implementation may be subject to additional terms and conditions"

Means that using this would be in breach, however I'm hopeful that Amazon will allow it.

**Comment by sammachin** [comment]
@flooie which branch of my code did you base this from? it looks to have some stuff that was in Lenny's code which I thought I'd already cleaned up like the json parsing.

**Comment by flooie** [comment]
@sammachin - Sam I'm actually a lawyer in the US  in my day job- could you send me the link to the terms of service so I can review them.

**Comment by sammachin** [comment]
@flooie Its section 2m of this doc https://developer.amazon.com/edw/avs_requirements.html (you might need to be logged in to your developer account to view)

The guys in the AVS evangelism team are trying to get it confirmed from Amazon Legal, after all the Alexa Fund invested in Snowboy so it would seem a bit silly to block it!

**Comment by flooie** [comment]
Let me poke around my legal network and see if I can get the answer.  

Also - I mostly used v11 - to base mine.  its still rough but seems to have most of the radio streams working.

**Comment by xuchen** [comment]
Sorry for coming late to this: @sammachin did you hear from AVS on legal? We have very good connection with the Alexa team and can work on this as well.

**Comment by tySwift93** [comment]
I'm curious, did anyone ever continue on with this?  I'd love to be able to try this out but I'm not sure that it's all hooked up and ready to go.

**Comment by xuchen** [comment]
@tySwift93 I was told last Friday that the legal ban on using a hotword with AVS will be lifted *this week*. There won't be any announcement, but will go quietly. If people are in a hurry to get it, I can help to get a written confirmation from AVS first.

AlexaPi seemed not to have too much update recently. So my bet is that the pull request still works.

**Comment by tySwift93** [comment]
I tried this pull request but it doesn't work like it should. Instead it doesn’t seem to do anything at all.  Have you gotten it to work?

**Comment by xuchen** [comment]
Terms are updated!

https://developer.amazon.com/public/solutions/alexa/alexa-voice-service/support/terms-and-agreements

@sammachin care about merging this PR?

**Comment by sammachin** [comment]
I've finally had some time to look at this project, I've spent the last week refactoring the code to be a lot more modular so that we can support multiple different setups and different ways of triggering eg, button, Spinx, Snowboy etc. I'm going to close this PR but will try and incorporate but where I can then hopefully we can move forward on the new modular codebase.

**Pull request closed without merging**
